### ISSUE TITLE
telldus-*.js does not exist

### ISSUE THREAD

**Issue by jrydval** [emiloberg/node-red-contrib-telldus#1]
Thank you for your library! Seems to be precisely what I am looking for.

I have just a small problem - probably with the file names:

```
21 Mar 18:24:13 - [info] Node-RED version: v0.10.4
21 Mar 18:24:13 - [info] Node.js  version: v0.10.36
21 Mar 18:24:13 - [info] Loading palette nodes
21 Mar 18:24:33 - [warn] ------------------------------------------
21 Mar 18:24:33 - [warn] [telldus-in] Error: /home/pi/Development/Node.js/node-red/node_modules/node-red-contrib-telldus/telldus/telldus-in.js does not exist
21 Mar 18:24:33 - [warn] [telldus-out] Error: /home/pi/Development/Node.js/node-red/node_modules/node-red-contrib-telldus/telldus/telldus-out.js does not exist
21 Mar 18:24:33 - [warn] [telldus-input] Error: /home/pi/Development/Node.js/node-red/node_modules/node-red-contrib-telldus/telldus/telldus-input.js does not exist
21 Mar 18:24:33 - [warn] ------------------------------------------
21 Mar 18:24:33 - [info] User Directory : /home/pi/.node-red
21 Mar 18:24:33 - [info] Flows file     : /home/pi/.node-red/flows_bobule.json
21 Mar 18:24:33 - [info] Server now running at http://127.0.0.1:1880/
21 Mar 18:24:33 - [info] Starting flows
21 Mar 18:24:33 - [info] Started flows
^C21 Mar 18:24:52 - [info] Stopping flows
```

When I rename tellstick-*.* to telldus-*.* then I can see the nodes in the palette, but it doesn't discover my devices (input) and cannot be configured (output).

**Comment by emiloberg** [comment]
Hi!

Happy you found your way over here! As the readme states, this is still a work in progress. But, it's should be more or less "done", I've been running it myself for quite some time now.

Unfortunately I'm out of country and away from my Tellstick for two more weeks so I'm coding in the blind here, but that error you're getting should be a package.json problem. I just committed some new code which should solve the problem.

Please tell me how it goes! And if you're getting any other errors (or have suggestions) feel more than welcome to open issues!

**Comment by jrydval** [comment]
```
                                                                                  Thank you Elim for quick response. I will test it in a few days. ‎Regards,Jan                                                                                                                                                                                                                                                                                                                                        Sent from my Brebera 10 smartphone.                                                                                                                                                                                                                From: Emil ÖbergSent: úterý, 24. března 2015 7:03To: emiloberg/node-red-contrib-telldusReply To: emiloberg/node-red-contrib-telldusCc: jrydvalSubject: Re: [node-red-contrib-telldus] telldus-*.js does not exist (#1)Hi!
```

Happy you found your way over here! As the readme states, this is still a work in progress. But, it's should be more or less "done", I've been running it myself for quite some time now.

Unfortunately I'm out of country and away from my Tellstick for two more weeks so I'm coding in the blind here, but that error you're getting should be a package.json problem. I just committed some new code which should solve the problem.

Please tell me how it goes! And if you're getting any other errors (or have suggestions) feel more than welcome to open issues!

—Reply to this email directly or view it on GitHub.

**Comment by jrydval** [comment]
Now it works fine.

Thanks!
