### ISSUE TITLE
Unable to install node on windows 10, surface pro 2

### ISSUE THREAD

**Issue by mohity5** [emiloberg/node-red-contrib-telldus#10]
Hello,

I am designer new to development environment. I am trying to install the tell-stick node on my surface pro_2 (windows 10).

However, when I execute the "npm install telldus" command, I get the following error. Please have a look and let me know how to solve this.

> telldus@1.1.0 install C:\Users\EIT-HII_PROJECT.node-red\node_modules\telldus
> node-gyp configure build

C:\Users\EIT-HII_PROJECT.node-red\node_modules\telldus>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  telldus.cc
..\telldus.cc(166): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\EIT-H
II_PROJECT.node-red\node_modules\telldus\build\telldus.vcxproj]
..\telldus.cc(216): error C3861: 'localtime': identifier not found [C:\Users\EIT-HII_PROJECT.node-red\node_modules\tel
ldus\build\telldus.vcxproj]
..\telldus.cc(216): error C3861: 'strftime': identifier not found [C:\Users\EIT-HII_PROJECT.node-red\node_modules\tell
dus\build\telldus.vcxproj]
..\telldus.cc(350): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\EIT-H
II_PROJECT.node-red\node_modules\telldus\build\telldus.vcxproj]
..\telldus.cc(892): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [C:\Users\EIT-HII_PROJ
ECT.node-red\node_modules\telldus\build\telldus.vcxproj]
..\telldus.cc(893): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [C:\Users\EIT-HII_PROJ
ECT.node-red\node_modules\telldus\build\telldus.vcxproj]
..\telldus.cc(894): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [C:\Users\EIT-HII_PROJ
ECT.node-red\node_modules\telldus\build\telldus.vcxproj]
..\telldus.cc(926): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [C:\Users\EIT-HII_PROJ
ECT.node-red\node_modules\telldus\build\telldus.vcxproj]
..\telldus.cc(927): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [C:\Users\EIT-HII_PROJ
ECT.node-red\node_modules\telldus\build\telldus.vcxproj]
..\telldus.cc(928): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [C:\Users\EIT-HII_PROJ
ECT.node-red\node_modules\telldus\build\telldus.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\EIT-HII_PROJECT.node-red\node_modules\telldus
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "telldus"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! telldus@1.1.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telldus@1.1.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the telldus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs telldus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls telldus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\EIT-HII_PROJECT.node-red\npm-debug.log

Please lemme know if some additional information is required.

**Comment by fgeorgsson** [comment]
See [Unable to install on Windows](https://github.com/Hexagon/node-telldus/issues/73) for the node-telldus dependency. This is not an error in node-red-contrib-tellstick.

**Comment by emiloberg** [comment]
Thanks @pcguru!
