### ISSUE TITLE
not in npm registry

### ISSUE THREAD

**Issue by kleinerzwerg** [emiloberg/node-red-contrib-telldus#2]
hi,
can u help me with this error message:

npm ERR! 404 'node-red-contrib-telldus' is not in the npm registry

**Comment by emiloberg** [comment]
Well... the error message is correct ;) 

It is not in the NPM registry yet, as it's still a work in progress. However, feel free to clone it from Github!

**Comment by emiloberg** [comment]
Or wait a few days and I'll have it on NPM!

**Comment by kleinerzwerg** [comment]
This would be great! :)

Emil Öberg notifications@github.com schrieb am Fr., 10. Apr. 2015 09:29:

**Comment by emiloberg** [comment]
Hi!
It's now published on NPM! 

Install by following the readme: https://www.npmjs.com/package/node-red-contrib-tellstick

Feel free to come with any feedback!
