### ISSUE TITLE
how to???

### ISSUE THREAD

**Issue by strelniece** [emiloberg/node-red-contrib-telldus#3]
hi,

new to node red and my forst try is to set up my tellstick to work with it. 
But I just don't get how to send commands to the out-node. Right now I can get it to work if I define method in the out-node itself but I cant get it to react with message set in inject node. Also I can't get it to react with message sent via mqtt.

If I can get some help with this, I can happly share my flow with me for others to see.

**Comment by emiloberg** [comment]
Hi!

The output node wants a message formatted in a special way (just like any other node which takes an input). The [format is specified in the README](https://github.com/emiloberg/node-red-contrib-tellstick#passing-data-to-the-out-node).

So what you want to do is that you want to send a payload which looks like this:

```
msg: {
    device: 1,
        // Integer, device ID. 
        // The Device IDs are displayed in the "Configure devices"
        // dialog (se further down in this README).
    method: 'turnon',
        // Valid methods: turnoff, turnon, dim, bell, learn
        // if dim is supplied so must dimlevel be.
        // method may also be an integer:
        //      0 (for turnoff)
        //      1 (for turnon)
        //      2 (for dim)
        //      3 (for bell)
        //      4 (for learn)
    dimlevel: 100
        // Only taken into account if method is "dim".
        // Valid input: 0-255, where 255 is 100% and 0 is off.
}
```

The inject node can not do this itself (it can only send a time/string/blank payload). So you need to wire the inject node to a _function_ node where you create the object which will then be sent into the Tellstick Out Node.

Here's an example with an inject node where you can set the Tellstick _Device ID_ in the inject node. This id is then sent to the _function_ node. In the function node the id is picked up and a new message is created (with that id in it) which is then passed on to the Tellstick out node.

(To find out your device IDs: Click on an Tellstick Out node and then click the blue configure button to see all configured devices and their ID:s).

The way Node-RED works each node sends a message to the next node. To inspect how that message looks, wire a _debug_ node from the output of a node.

```
[{"id":"b8f02fe7.470fd","type":"inject","name":"","topic":"","payload":"4","payloadType":"string","repeat":"","crontab":"","once":false,"x":476,"y":932,"z":"88d906e1.7726f8","wires":[["f6f3d46e.090c28"]]},{"id":"44bfc101.bb404","type":"tellstick-out","name":"","device":"","devicefriendlyname":"","method":"","dimlevel":0,"x":921,"y":932,"z":"88d906e1.7726f8","wires":[]},{"id":"f6f3d46e.090c28","type":"function","name":"","func":"msg = {\n    device: msg.payload,\n    method: 'turnon'\n};\n\nreturn msg;","outputs":1,"valid":true,"x":701,"y":932,"z":"88d906e1.7726f8","wires":[["44bfc101.bb404"]]}]
```

Did that work for you?

**Comment by emiloberg** [comment]
And you've to do it the same way with the MQTT integration. Add an MQTT input node > do some magic with a function node > Tellstick Out node.

**Comment by strelniece** [comment]
hej,

tänker göra antagandet att du kan svenska ;)

det funkade... är inne på tredje dagen med node-red installerat så 
försöker trassla ut alla detaljer. När man kan skicka direkt och inte, 
och andra små detaljer man inte tänker på rakt av. Det är ju väldig 
enkaelt, men gjorde det kanske för enkelt för mig.

då ska vi se om jag får ihop min toggle-funktion som jag idag kör som 
bash-script...

men tack för hjälp och nod

//fia

Den 2015-04-16 14:54, Emil Öberg skrev:

**Comment by emiloberg** [comment]
Bra antagande ;)

Det finns en Node-RED Google Group som jag rekommenderar starkt för alla dina frågor kring Node-RED. Den är väldigt aktiv och alla är hjälpsamma! https://groups.google.com/forum/#!forum/node-red

Och om du undrar någon om just den här noden så är det såklart bara att fråga på! Eller om du har önskemål om utveckling eller förslag eller så!

Lycka till!
