### ISSUE TITLE
Failing telldus installation on Raspberry Pi

### ISSUE THREAD

**Issue by fredrikjohnsson** [emiloberg/node-red-contrib-telldus#5]
This is the output when I'm trying to run "nom install tellsdus" in the "~./node-red/" folder. 

pi@OW01 ~/.node-red $ npm install telldus
|

> telldus@0.0.9 install /home/pi/.node-red/node_modules/telldus
> node-gyp configure build

make: Entering directory '/home/pi/.node-red/node_modules/telldus/build'
  CXX(target) Release/obj.target/telldus/telldus.o
../telldus.cc: In function ‘v8::Localv8::Object telldus_v8::GetSupportedMethods(int, int)’:
../telldus.cc:68:42: error: no matching function for call to ‘v8::Array::New()’
../telldus.cc:68:42: note: candidate is:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:2417:23: note: static v8::Localv8::Array v8::Array::New(v8::Isolate_, int)
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:2417:23: note:   candidate expects 2 arguments, 0 provided
../telldus.cc:72:68: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:73:68: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:74:65: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:75:67: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:76:65: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:77:63: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:78:65: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:79:65: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:80:66: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc: In function ‘v8::Localv8::String telldus_v8::GetDeviceType(int, int)’:
../telldus.cc:88:45: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:89:44: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:90:44: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:92:12: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc: In function ‘v8::Localv8::Object telldus_v8::GetDeviceStatus(int, int, int)’:
../telldus.cc:98:40: error: no matching function for call to ‘v8::Object::New()’
../telldus.cc:98:40: note: candidate is:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:2388:24: note: static v8::Localv8::Object v8::Object::New(v8::Isolate_)
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../telldus.cc:102:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:102:48: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:105:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:105:48: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:108:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:108:48: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:109:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:109:66: error: no matching function for call to ‘v8::Number::New(int&)’
../telldus.cc:109:66: note: candidate is:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note: static v8::Localv8::Number v8::Number::New(v8::Isolate_, double)
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../telldus.cc:112:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:112:48: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc: In function ‘v8::Localv8::Object telldus_v8::GetDevice(telldus_v8::telldusDeviceInternals)’:
../telldus.cc:121:37: error: no matching function for call to ‘v8::Object::New()’
../telldus.cc:121:37: note: candidate is:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:2388:24: note: static v8::Localv8::Object v8::Object::New(v8::Isolate_)
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../telldus.cc:122:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:122:41: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:123:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:123:69: error: no matching function for call to ‘v8::Number::New(int&)’
../telldus.cc:123:69: note: candidate is:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note: static v8::Localv8::Number v8::Number::New(v8::Isolate_, double)
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../telldus.cc:124:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:125:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:125:42: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:126:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:126:45: error: ‘New’ is not a member of ‘v8::String’
../telldus.cc:127:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../telldus.cc:128:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h: In function ‘v8::Handlev8::Value telldus_v8::getDevicesFromInternals(std::list<telldus_v8::telldusDeviceInternals>)’:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../telldus.cc:141:17: error: within this context
../telldus.cc:144:47: error: invalid conversion from ‘std::list<telldus_v8::telldusDeviceInternals>::size_type {aka unsigned int}’ to ‘v8::Isolate_’ [-fpermissive]
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:2417:23: error:   initializing argument 1 of ‘static v8::Localv8::Array v8::Array::New(v8::Isolate_, int)’ [-fpermissive]
../telldus.cc:151:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
../telldus.cc: At global scope:
../telldus.cc:197:35: error: variable or field ‘DeviceEventCallbackWorking’ declared void
../telldus.cc:197:35: error: ‘uv_work_t’ was not declared in this scope
../telldus.cc:197:46: error: ‘req’ was not declared in this scope
../telldus.cc:837:1: error: expected ‘}’ at end of input
../telldus.cc: In function ‘v8::Handlev8::Value telldus_v8::getDevicesFromInternals(std::list<telldus_v8::telldusDeviceInternals>)’:
../telldus.cc:153:3: warning: control reaches end of non-void function [-Wreturn-type]
../telldus.cc: In function ‘v8::Localv8::String telldus_v8::GetDeviceType(int, int)’:
../telldus.cc:94:3: warning: control reaches end of non-void function [-Wreturn-type]
telldus.target.mk:83: recipe for target 'Release/obj.target/telldus/telldus.o' failed
make: *_\* [Release/obj.target/telldus/telldus.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/telldus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.5+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/.node-red/node_modules/telldus
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 4.1.5+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "telldus"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! telldus@0.0.9 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telldus@0.0.9 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the telldus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls telldus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log

Please let me know if something else is needed.

**Comment by emiloberg** [comment]
Hi,

This module use the [Telldus wrapper](https://github.com/Hexagon/node-telldus) (which you're installing with the `npm install telldus` command). Looking at [this issue](https://github.com/Hexagon/node-telldus/issues/65) it looks like node-telldus doesn't work with Node 0.12. Could try Node v0.10.40?

Please come back to me and let me know how it goes (and I'll update the README accordingly). But as the problem is with node-telldus (which is a dependency of this module), any issues should be posted at [their place](https://github.com/Hexagon/node-telldus/issues/65).

**Comment by freber** [comment]
Noooo! I'm also suffering from this issue.

**Comment by emiloberg** [comment]
@freber If you run with Node 0.10.x, does it work for you?

**Comment by emiloberg** [comment]
@freber and @fredrikjohnsson Here's an easy way to switch between Node versions: https://www.npmjs.com/package/n

**Comment by fredrikjohnsson** [comment]
I've tried 0.10.40 (on a different machine) and it works! I can send commands but no sensor values where received in Node-Red, only with tdtool.

**Comment by emiloberg** [comment]
Thank you, then we know for sure that it's a problem with Node 0.12+.

As for you not receiving sensor data. Make sure you've the [in-node set up properly](https://github.com/emiloberg/node-red-contrib-tellstick#usage-in-node). If the problem persists, please open a new issue.

**Comment by freber** [comment]
@emiloberg Yes, 0.10.x works fine! I downgraded and it works, also with sensor inputs.

**Comment by freber** [comment]
also with sensors

**Comment by emiloberg** [comment]
Hi guys,

The underlining dependency has just updated with support for newer Node versions. (See https://github.com/Hexagon/node-telldus/issues/65 )

To make this package work on Node 0.12+ reinstall the dependency by:

```
cd node-red-contrib-tellstick
npm uninstall telldus
npm install telldus
```

That should be it, let me know if something's not working!
