### ISSUE TITLE
Error installing node-telldus

### ISSUE THREAD

**Issue by FirstLobster** [emiloberg/node-red-contrib-telldus#6]
Hi, I'm running linux mint 17 and using node v0.10.40
both telldus core and dev are installed and node-red works fine.
When i run the 'npm install telldus' command im left with then following error message.

sudo npm install telldus
/

> telldus@0.0.9 install /home/ServerUser/node_modules/telldus
> node-gyp configure build

make: Entering directory `/home/ServerUser/node_modules/telldus/build'
  CXX(target) Release/obj.target/telldus/telldus.o
make: g++: Command not found
make: *** [Release/obj.target/telldus/telldus.o] Error 127
make: Leaving directory`/home/ServerUser/node_modules/telldus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/ServerUser/node_modules/telldus
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! telldus@0.0.9 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telldus@0.0.9 install script.
npm ERR! This is most likely a problem with the telldus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls telldus
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "telldus"
npm ERR! cwd /home/ServerUser/.node-red
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

I'm kinda green on linux so any help would be appreciated.

**Comment by emiloberg** [comment]
As this is a problem you're experiencing when installing node-telldus and not this package, I bet you get better answers asking them, here: https://github.com/Hexagon/node-telldus

However, it looks like you're either missing the command `make` or `g++`/`gcc`. Make sure you've both installed.
