### ISSUE TITLE
Minor issue in packages.json

### ISSUE THREAD

**Issue by Hexagon** [emiloberg/node-red-contrib-telldus#8]
Hey!

https://github.com/emiloberg/node-red-contrib-tellstick/blob/master/package.json#L43

That line should be changed to "**>=**1.0.0"

Now npm outputs an warning that shouldn't need to be there.

`````` bash
npm WARN unmet dependency /home/.../node_modules/node-red-contrib-tellstick requres telldus@'1.0.0' but will load
npm WARN unmet dependency /home/.../node_modules/telldus,
npm WARN unmet dependency which is version 1.1.0```
``````

**Comment by emiloberg** [comment]
Wops, missed this issue! Thanks for this!
